-- 1.
-- SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDE, PROJEKTAS.PAVADINIMAS
-- FROM DARBUOTOJAS LEFT JOIN PROJEKTAS ON PROJEKTAS_ID = ID

-- 2.
-- SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDE, PROJEKTAS.PAVADINIMAS
-- FROM DARBUOTOJAS LEFT JOIN PROJEKTAS ON PROJEKTAS_ID = ID
-- WHERE PROJEKTAS.PAVADINIMAS = 'Kaunas'

-- 3.

-- SELECT *
-- FROM DARBUOTOJAS LEFT JOIN PROJEKTAS ON PROJEKTAS_ID = ID
-- WHERE PAVADINIMAS = 'Registru Centras' AND PAREIGOS = 'Testuotojas'

-- 4.

--SELECT VARDAS, PAVARDE, PAVADINIMAS
--FROM DARBUOTOJAS LEFT JOIN PROJEKTAS ON PROJEKTAS_ID = ID
--WHERE PAVADINIMAS = 'Izola' AND
--ASMENSKODAS LIKE '4%'

-- 5.

--SELECT SKYRIUS_PAVADINIMAS, COUNT(*) AS DARBUOTOJU_SKAICIUS
--FROM DARBUOTOJAS
--GROUP BY SKYRIUS_PAVADINIMAS

-- 6.

--SELECT SKYRIUS_PAVADINIMAS, COUNT(*) AS DARBUOTOJU_SKAICIUS
--FROM DARBUOTOJAS
--GROUP BY SKYRIUS_PAVADINIMAS
--HAVING COUNT(*) > 4

-- 7.

--SELECT VARDAS, PAVARDE, SKYRIUS_PAVADINIMAS
--FROM DARBUOTOJAS
--WHERE PAREIGOS NOT LIKE '%vadov%'
--GROUP BY VARDAS, PAVARDE, SKYRIUS_PAVADINIMAS

-- 8.

--INSERT INTO DARBUOTOJAS (ASMENSKODAS, VARDAS, PAVARDE, DIRBANUO, GIMIMOMETAI)
--VALUES ('3880711789', 'Pranas', 'Logis', '2009-11-12', '1988-11-14')

-- 9.

--SELECT VARDAS, PAVARDE, PAVADINIMAS
--FROM DARBUOTOJAS LEFT JOIN SKYRIUS ON ASMENSKODAS = VADOVAS_ASMENSKODAS

-- 10.

 SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDE, PROJEKTAS.PAVADINIMAS
 FROM DARBUOTOJAS LEFT JOIN PROJEKTAS ON PROJEKTAS_ID = ID
 GROUP BY DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDE, PROJEKTAS.PAVADINIMAS
 HAVING COUNT(*) > 4